name: QA

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-scraper-qa:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: pyproject.toml
          architecture: x64

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -e .[lint,check,scripts,test]

      - name: Check black formatting
        run: inv lint-black

      - name: Check ruff
        run: inv lint-ruff

      - name: Check pyright
        run: inv check-pyright